apiVersion: v1
kind: Pod
metadata:
  name: threatguard-target-pod
  namespace: threatguard
  labels:
    app.kubernetes.io/name: cloudnative-threatguard
    app.kubernetes.io/component: simulation-target
    security.threatguard.io/tier: runtime-monitored
spec:
  hostPID: false
  hostIPC: false
  hostNetwork: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: simulation-target
      image: alpine:3.20
      command: ["/bin/sh", "-c", "sleep 86400"]
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
