apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: tp-006-outbound-network
  labels:
    app.kubernetes.io/name: cloudnative-threatguard
    app.kubernetes.io/component: runtime-ebpf
    security.threatguard.io/rule: RUNTIME-006
    security.threatguard.io/mitre: T1071
spec:
  kprobes:
    - call: "sys_enter_connect"
      syscall: true
      args:
        - index: 0
          type: "int"      # socket fd
        - index: 1
          type: "sockaddr" # remote destination address
      selectors:
        - matchNamespaces:
            - "threatguard"
          matchActions:
            - action: Post
              rateLimit: "10m"
