apiVersion: v1
kind: Pod
metadata:
  name: privileged-debug-pod
  namespace: threatguard
  labels:
    app: privileged-debug-pod
    security.threatguard.io/profile: misconfigured
spec:
  containers:
  - name: debug
    image: alpine:3.19
    command: ["/bin/sh", "-c", "sleep 3600"]
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add: ["SYS_ADMIN"]
