apiVersion: v1
kind: Pod
metadata:
  name: hostpath-mount-pod
  namespace: threatguard
  labels:
    app: hostpath-mount-pod
    security.threatguard.io/profile: misconfigured
spec:
  containers:
  - name: inspector
    image: alpine:3.19
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: host-root
      mountPath: /host
  volumes:
  - name: host-root
    hostPath:
      path: /
